version: "3.9"

services:
  api:
    container_name: api_betapp 
    env_file: ./.env
    build:
      context: ./
      dockerfile: dockerfile.dev
    command: yarn dev
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "./:/usr/betapp/api/"
      - "./node_modules:/usr/betapp/api/node_modules"
    networks:
      - api-net

  db:
    image: mysql
    container_name: db_betapp
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - api-net

networks:
  api-net:
    driver: bridge
